### ISSUE TITLE
Feedback Sprint 2

### ISSUE THREAD

**Issue by MarciaMillanao** [PaulaAraya/scl-2018-05-bc-core-am-datadashboard#1]
Hola chicas!
Estuve revisando el avance que llevan y tengo algunos comentarios:

1.- Revisen bien su planificación, ven los tiempos de entrega, aún no han comenzado a desarrollar código en js.

2.- Les recomiendo usar nombre de identificadores (variables en js, clases o id en html & css) bien descriptivos y en inglés.

3.- Utilicen todo el HTML semántico, con eso me refiero a las etiquetas `<header></header> <section></section> <article></article> <aside></aside> <nav></nav> <footer></footer>`.

4.- Si van a utilizar Bootstrap, elijan utilizar cdn o los archivos descargado en su proyecto, no es necesario tener ambas opciones.

5.- Recuerden revisar el orden de sus script al final de su HTML.

6.- Usen los issues para coordinarse y comunicarse entre ustedes.

7.- Utilicen milestones para ver el avance de los issues, esto es como un trello pero en github (similar) , les dejo dos vídeos de guía [https://www.youtube.com/watch?v=9SZSHGA95x4](url)
[https://www.youtube.com/watch?v=nI5VdsVl0FM](url).

Vamos con todo...!

**Comment by CarolinAraya** [comment]
Gracias Marcia!! Estamos en el js ahora mismo.

**Comment by PaulaAraya** [comment]
Gracias Marcia!
Tengo preguntas sobre css intento que la barra menú y el header sean fijos intenté con position: fixed; y con overflow: none; pero no me funcionan
